# Generated by Django 4.2.7 on 2025-07-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사들',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('process_type', models.CharField(choices=[('import', '가져오기'), ('classification', '분류'), ('export', '내보내기')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_successful', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '처리 로그',
                'verbose_name_plural': '처리 로그들',
                'db_table': 'processing_logs',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('income', '수익'), ('expense', '비용'), ('neutral', '중립')], default='expense', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounting.company')),
            ],
            options={
                'verbose_name': '계정과목',
                'verbose_name_plural': '계정과목들',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('income_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expense_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(choices=[('income', '입금'), ('expense', '출금')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_classified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.company')),
            ],
            options={
                'verbose_name': '거래 내역',
                'verbose_name_plural': '거래 내역들',
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['transaction_date'], name='transaction_transac_0d716a_idx'), models.Index(fields=['company'], name='transaction_company_e2b105_idx'), models.Index(fields=['category'], name='transaction_categor_bf503b_idx'), models.Index(fields=['is_classified'], name='transaction_is_clas_753561_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassificationKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='accounting.category')),
            ],
            options={
                'verbose_name': '분류 키워드',
                'verbose_name_plural': '분류 키워드들',
                'db_table': 'classification_keywords',
                'unique_together': {('keyword', 'category')},
            },
        ),
    ]
